# Generated by Django 2.1 on 2018-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('uage', models.PositiveIntegerField()),
            ],
        ),
    ]
