# Generated by Django 2.1 on 2018-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='testClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.ForeignKey(on_delete='CASCADE', related_name='t_id', to='polls.Users')),
                ('t_tid', models.ForeignKey(on_delete='CASCADE', related_name='t_tid', to='polls.Users')),
            ],
        ),
    ]
