# Generated by Django 2.1.3 on 2018-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181122_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete='CASCADE', related_name='event_id', to='polls.Events')),
                ('master', models.ForeignKey(on_delete='CASCADE', related_name='master', to='polls.Users')),
                ('participator', models.ForeignKey(on_delete='CASCADE', related_name='participator', to='polls.Users')),
            ],
        ),
    ]
