# Generated by Django 2.1.3 on 2018-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181123_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inviter', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='connection',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='master',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='participator',
        ),
        migrations.RemoveField(
            model_name='events',
            name='initiator',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.AddField(
            model_name='join',
            name='event_id',
            field=models.ForeignKey(on_delete='CASCADE', to='polls.Events'),
        ),
        migrations.AddField(
            model_name='join',
            name='user_id',
            field=models.ForeignKey(on_delete='CASCADE', to='polls.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='initiator',
            field=models.ManyToManyField(through='polls.Join', to='polls.Users'),
        ),
    ]
