# Generated by Django 2.1.3 on 2018-11-24 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181123_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 32, 37, 52006)),
        ),
    ]
