# Generated by Django 2.1.3 on 2018-11-24 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20181124_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='events',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 17, 30, 30, 668814)),
        ),
    ]
