# Generated by Django 2.1.3 on 2018-11-24 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20181124_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 17, 48, 20, 996333)),
        ),
    ]
